export const DURACAO_BUCKET_SEGUNDOS = 10;
export const SEGUNDOS_POR_MINUTO = 60;
export const BUCKETS_POR_MINUTO = SEGUNDOS_POR_MINUTO / DURACAO_BUCKET_SEGUNDOS;

export const JANELA_BASELINE_MINUTOS = 10;
export const BUCKETS_JANELA_BASELINE = JANELA_BASELINE_MINUTOS * BUCKETS_POR_MINUTO;
export const BUCKETS_MINIMOS_PARA_BASELINE = BUCKETS_POR_MINUTO;

export const BASELINE_MENSAGENS_MINIMO = 3;
export const RAZAO_VOLUME_MINIMA_PARA_PICO = 2;

export const FATOR_SATURACAO_VOLUME = 0.55;
export const PESO_VOLUME_NO_SCORE_CHAT = 0.7;
export const PESO_DENSIDADE_NO_SCORE_CHAT = 0.3;

export const SCORE_CHAT_MINIMO_PARA_PICO = 0.6;

export const USUARIOS_DISTINTOS_MINIMO_RISADA_COLETIVA = 3;
export const BONUS_RISADA_COLETIVA = 0.1;

export const MAXIMO_REPETICOES_CARACTERE = 3;
export const TAMANHO_MAXIMO_MENSAGEM_ANALISADA = 500;
export const INTENSIDADE_MAXIMA_REPETICAO = 12;

export const INTERVALO_AGRUPAMENTO_PICOS_SEGUNDOS = 45;
export const DISTANCIA_MINIMA_ENTRE_MOMENTOS_SEGUNDOS = 60;
